In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [10]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [11]:
a.shape

(3,)

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [19]:
b[1, 2]

6

In [23]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.full((3,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.random((3, 5))

array([[0.75395874, 0.93403317, 0.30889956, 0.37427293, 0.78808412],
       [0.33220856, 0.18399217, 0.82230615, 0.57883874, 0.47523284],
       [0.80497247, 0.71451569, 0.38705512, 0.8704797 , 0.65882234]])

In [31]:
a = np.array([1, 2, 3])

In [32]:
a.dtype

dtype('int64')

In [33]:
b = np.array([1.0, 2.0, 3.0])
b.dtype

dtype('float64')

In [34]:
a = np.array([1,2,3], dtype=float)
a.dtype

dtype('float64')

In [35]:
a

array([1., 2., 3.])

In [36]:
a = np.array([1, 2, 3, 4, 5])
a[1:4]

array([2, 3, 4])

In [38]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
b[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [40]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[5:]

array([5, 6, 7, 8, 9])

In [41]:
a[5:] = 10

In [42]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [43]:
b = np.array([0,1,2,3,4,5,6,7,8,9])
b[2:5]

array([2, 3, 4])

In [44]:
b[2:5] = np.array([20,30,40])
b

array([ 0,  1, 20, 30, 40,  5,  6,  7,  8,  9])

In [46]:
a = np.array([1,2,3,4,5])
a_slice = a[1:3]

In [48]:
a_slice[0] = 9

In [49]:
a

array([1, 9, 3, 4, 5])

In [52]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
mask = [True, True, True, True, True, False, False, False, False, True]

In [53]:
a[mask]

array([0, 1, 2, 3, 4, 9])

In [55]:
a < 5 

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [56]:
a[a < 5]

array([0, 1, 2, 3, 4])

In [57]:
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [59]:
b = np.array([20, 50, None, 35, 90, None, 110])
b[b == None] = 0

In [60]:
b

array([20, 50, 0, 35, 90, 0, 110], dtype=object)

In [62]:
a = np.array([[1,2], [3,4], [5,6]])
mask = np.array([[False, False], [True, False], [True, True]])
a[mask]

array([3, 5, 6])

In [63]:
a = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
a[[1, 5, 9]]

array([10, 50, 90])

In [64]:
a[[5, 1, 9]]

array([50, 10, 90])

In [65]:
a[[5, 1, 5, 9, 9, 5, 5]]

array([50, 10, 50, 90, 90, 50, 50])

In [66]:
a[[5,1,9]] = 100
a

array([  0, 100,  20,  30,  40, 100,  60,  70,  80, 100])

In [67]:
a = np.array([[1,2], [3,4], [5,6]])
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [68]:
a = np.array([1,2,3,4,5])
a + 1

array([2, 3, 4, 5, 6])

In [69]:
2*a

array([ 2,  4,  6,  8, 10])

In [70]:
b = np.array([10,20,30,40,50])
a+b

array([11, 22, 33, 44, 55])

In [71]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

a+b

array([[ 6,  8],
       [10, 12]])

In [74]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [75]:
a*b

array([[ 5, 12],
       [21, 32]])

In [76]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [77]:
a > 3

array([[False, False],
       [False,  True]])

In [78]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [80]:
a > b

array([False, False,  True, False])

In [82]:
np.array_equal(a, np.array([1,2,9,4]))

False

In [84]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])

a | b

array([1, 1, 1, 0])

In [85]:
a = np.array([1,2,3,4])
np.sum(a)

10

In [86]:
b = np.array([[1,2,3], [4,5,6]])
np.sum(b)

21

In [87]:
np.sum(b, axis=0)

array([5, 7, 9])

In [88]:
np.sum(b, axis=1)

array([ 6, 15])

In [91]:
np.max(a)

4

In [97]:
np.min(b, axis=0)

array([1, 2, 3])

In [98]:
np.mean(a)

2.5

In [99]:
np.median(a)

2.5

In [100]:
c = np.array([1,2,3,4])
d = np.array([2,4,6,8])

np.any(c == 2)

True

In [101]:
np.any(c==10)

False

In [103]:
np.all(c < 4)

False

In [104]:
np.any(c%2 == 0)

True

In [105]:
np.all(c%2 == 0)

False

In [107]:
np.any(d%2 == 0)

True

In [108]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

In [109]:
a+b

array([[11, 22, 33],
       [14, 25, 36]])

In [110]:
a = np.array([1,2,3],
             [1,2,3],
             [1,2,3])
b = np.array([[10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])

a+b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [111]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [112]:
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [113]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [114]:
a.reshape((5,6))

ValueError: cannot reshape array of size 4 into shape (5,6)

In [115]:
b = np.array([[1,2,3],
              [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [117]:
a = np.array([4,1,3,5,2])
np.sort(a)

array([1, 2, 3, 4, 5])

In [118]:
a

array([4, 1, 3, 5, 2])

In [120]:
mask = np.argsort(a)

In [121]:
a[mask]

array([1, 2, 3, 4, 5])